server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:file:./database/train
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

  flyway:
    enabled: true
    locations:
      - classpath:db/migration
      - filesystem:/another/migration/directory
    baseline-on-migrate: true
